HappyCat/Controllers/CatController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Grpc.Core;
using HappyCat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Test.Models;
using Test.Repository;

namespace HappyCat.Controllers
{
    public class CatController : Controller
    {
        private readonly ICatRepository _catRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public IActionResult Index()
        {
            return View();          
        }

        public CatController(ICatRepository catRepository, IWebHostEnvironment webHostEnvironment)
        {
            _catRepository = catRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        [Authorize]
        public ViewResult AddNewCat(bool isSuccess = false)
        {
            ViewBag.IsSuccess = isSuccess;
            var path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot\\{"/lib/json/cat_breeds.json"}");
            var json = System.IO.File.ReadAllText(path);
            dynamic breedsJson = JsonConvert.DeserializeObject(json);
            ViewBag.Breeds = breedsJson;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddNewCat(CatModel catModel)
        {
            if (ModelState.IsValid)
            {
                if (catModel.CoverPhoto != null)
                {
                    string folder = "cats/cover/";
                    catModel.CoverImageUrl = await UploadImage(folder, catModel.CoverPhoto);
                }
                if (catModel.GalleryFiles != null && catModel.GalleryFiles.Count > 0)
                {
                    string gallery_folder = "cats/gallery/";
                    catModel.Gallery = new List<GalleryModel>();
                    foreach (IFormFile file in catModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadImage(gallery_folder, file)
                        };
                        catModel.Gallery.Add(gallery);
                    }
                }           
                int id = await _catRepository.AddNewCatAsync(catModel);
                if (id > 0)
                {
                    return RedirectToAction("AddNewCat", new { isSuccess = true });
                }
            }
            var path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot\\{"/lib/json/cat_breeds.json"}");
            var json = System.IO.File.ReadAllText(path);
            dynamic breedsJson = JsonConvert.DeserializeObject(json);
            ViewBag.Breeds = breedsJson;
            return View();
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {          
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;
            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);
            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return "/" + folderPath;
        }

        [Route("all-cats")]
        public async Task<ViewResult> GetAllCats()
        {
            var data = await _catRepository.GetAllCats();
            return View(data);
        }

        [Route("cat-details/{id:int:min(1)}", Name = "catDetailsRoute")]
        public async Task<ViewResult> GetCat(int id)
        {
            var data = await _catRepository.GetCatById(id);
            return View(data);
        }

        [Route("cat-delete/{id:int:min(1)}", Name = "catDeleteRoute")]
        public async Task<ViewResult> DeleteCat(CatModel catModel)
        {
            var data= await _catRepository.DeleteCat(catModel);
            return View("GetAllCats",data);
        }
    }
}

HappyCat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Happy Cat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
</head>
<body>
    <partial name="_header"/>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <partial name="_footer" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HappyCat/Views/Shared/_catCard.cshtml
@model CatModel
@inject Microsoft.AspNetCore.Identity.SignInManager<HappyCat.Models.ApplicationUser> _signInManager
<div class="card h-100 shadow-sm">
    <div class="card-text bg-light" style="z-index:2;">
        @if (User.IsInRole("Admin")){
             <a asp-route="catDeleteRoute" asp-route-id="@Model.Id" class="float-right mr-2" style="text-decoration:none">X</a>
        }     
    </div>
    <div class="card-img-top">
        <img class="img-fluid" src="@Model.CoverImageUrl">
    </div>
    <div class="card-body">
        <h3 class="card-title">@Model.Name</h3>
        <small class="text-muted">@Model.Type</small>
        <p class="card-text">@Model.Info</p>
        <a asp-route="catDetailsRoute" asp-route-id="@Model.Id" class="stretched-link"></a>
    </div>
</div>

HappyCat/Views/Shared/_footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Test - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

HappyCat/Views/Shared/_header.cshtml
@inject Test.Repository.ICatRepository _catRepository
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">@_catRepository.GetAppName()</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial" />
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cat" asp-action="GetAllCats">All Cats</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="AboutUs">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home"  asp-action="ContactUs">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>